version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: poi
      POSTGRES_PASSWORD: poi
      POSTGRES_DB: poidb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - poi-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@poi.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - poi-net

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - poi-net

  neo4j:
    image: neo4j:5
    container_name: neo4j
    environment:
      NEO4J_AUTH: neo4j/test1234
    ports:
      - "7474:7474"  # interface web
      - "7687:7687"  # bolt
    volumes:
      - neo4j_data:/data
    networks:
      - poi-net

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - poi-net

  trip-service:
    build:
      context: ./trip-service
      dockerfile: Dockerfile
    container_name: trip-service
    ports:
      - "8084:8084"
    depends_on:
      - postgres
      - mongodb
    networks:
      - poi-net


  city-service:
    build:
      context: ./city-service
      dockerfile: Dockerfile
    container_name: city-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - poi-net

  activity-service:
    build:
      context: ./activity-service
      dockerfile: Dockerfile
    container_name: activity-service
    ports:
      - "8083:8083"
    depends_on:
      - mongodb
    networks:
      - poi-net

  accommodation-service:
    build:
      context: ./accommodation-service
      dockerfile: Dockerfile
    container_name: accommodation-service
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    networks:
      - poi-net


  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - trip-service
      - city-service
      - activity-service
      - accommodation-service
    networks:
      - poi-net


volumes:
  pg_data:
  mongo_data:
  neo4j_data:

networks:
  poi-net:
    driver: bridge
