apiVersion: apps/v1
kind: Deployment
metadata:
  name: city-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: city-service
  template:
    metadata:
      labels:
        app: city-service
    spec:
      containers:
        - name: city-service
          image: city-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: city-service
spec:
  selector:
    app: city-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort
