server:
  port: 8084

spring:
  application:
    name: trip-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/poidb

  jackson:
    serialization:
      write-dates-as-timestamps: false
