server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: city-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/cities/**

        - id: accommodation-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/accommodations/**

        - id: activity-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/activities/**

        - id: trip-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/trips/**


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
