server:
  port: 8081

spring:
  application:
    name: city-service

  datasource:
    url: jdbc:postgresql://postgres:5432/poidb
    username: poi
    password: poi
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
